//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veg_Data_Analyser
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int Id { get; set; }
        public Nullable<int> task_number { get; set; }
        public string assesment { get; set; }
        public string inspection { get; set; }
        public string notice { get; set; }
        public string fellortrim { get; set; }
        public Nullable<System.DateTime> assessment_date { get; set; }
        public Nullable<int> meters_exposed { get; set; }
        public string task_progress { get; set; }
    }
}
